name: Deploy

on:
  push:
    branches: ["master"]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v2

      - name: Setup node version
        uses: actions/setup-node@v3
        with:
          node-version: 21.6.2

      - name: .env setting
        run: |
          echo "SPREADSHEETS_ID=${{ secrets.SPREADSHEETS_ID }}" >> .env
          echo "GAPI_KEY=${{ secrets.GAPI_KEY }}" >> .env
        
      - name: Install dependencies
        run: npm install
        
      - name: Build
        run: npm run build
